import os
import subprocess

# Nuclear assemblies search workflow No. 2

# Generated by ChatGPT

# Load organism → genetic code mapping
translation_table_file = "organisms_tables.txt"
genetic_code_map = {}
with open(translation_table_file) as f:
    for line in f:
        if ":" in line:
            org, code = line.strip().split(":")
            genetic_code_map[org.strip()] = int(code.strip())

# Read list of organisms and proteins
with open("organisms.txt") as f:
    organisms = [line.strip() for line in f.readlines()]

with open('proteins.txt') as f:
    proteins = [line.strip() for line in f.readlines()]

# Loop over organisms and proteins
for organism in organisms:
    genome_path = f"./organisms/{organism}/{organism}_genomic.fasta"
    if not os.path.exists(genome_path):
        print(f"[Warning] Genome not found for {organism}: {genome_path}")
        continue

    trans_table = genetic_code_map[organism]

    for protein in proteins:
        query_path = f"./input/{protein}.fasta"
        if not os.path.exists(query_path):
            print(f"[Warning] Protein query not found: {query_path}")
            continue

        print(f"[INFO] Running Miniprot: {protein} vs {organism}")

        output_dir = f"./organisms/{organism}/miniprot"
        os.makedirs(output_dir, exist_ok=True)

        output_txt = f"{output_dir}/{protein}_{organism}_miniprot.txt"
        output_fasta = f"{output_dir}/{protein}_{organism}_seq.fasta"

        # Run miniprot
        cmd = [
            f"miniprot",
            f"--trans",
            f"-t 10",
            f"-L 20",
            f"-O 7",
            f"-T {trans_table}",
            genome_path,
            query_path
        ]
        try:
            with open(output_txt, "w") as f_out:
                subprocess.run(cmd, stdout=f_out, stderr=subprocess.DEVNULL, check=True)
        except subprocess.CalledProcessError as e:
            print(f"[Error] Miniprot failed on {protein} vs {organism}")
            continue

        # Parse the output file
        with open(output_txt) as f_in, open(output_fasta, "w") as f_out:
            header = ""
            sequence = ""
            for line in f_in:
                line = line.strip()
                if not line:
                    continue
                if line.startswith("##STA"):
                    # Sequence line
                    if header and sequence:
                        f_out.write(f">{header}\n{sequence}\n")
                    sequence = line.split("\t", 1)[1] if "\t" in line else ""
                elif not line.startswith("#") and not line.startswith("##"):
                    # Parse alignment line
                    fields = line.split("\t")
                    if len(fields) < 10:
                        continue  # skip malformed
                    protein_id = fields[0]
                    db_id = fields[5]
                    start = fields[7]
                    end = fields[8]
                    clean_protein = protein.split(".")[0]
                    header = f"{db_id}_{start}_{end}_ribosomal_protein_{clean_protein}_{organism}_miniprot_nuclear"
            # Write last one
            if header and sequence:
                f_out.write(f">{header}\n{sequence}\n")

        print(f"[DONE] Translated FASTA saved to {output_fasta}")
