from Bio.Seq import Seq
import os

# Nuclear assemblies search workflow No. 4

# Generated by ChatGPT

translation_table_file = "organisms_tables.txt"
genetic_code_map = {}
with open(translation_table_file) as f:
    for line in f:
        if ":" in line:
            org, code = line.strip().split(":")
            genetic_code_map[org.strip()] = int(code.strip())

with open('proteins.txt') as f:
    proteins = [line.strip() for line in f.readlines()]

with open("organisms.txt") as f:
    organisms = [line.strip() for line in f.readlines()]

for organism in organisms:

    trans_table = genetic_code_map[organism]

    for protein in proteins:

        output_fasta = open(f"./organisms/{organism}/exonerate/{protein}_{organism}_seq.fasta", "w")

        file_path = f"./organisms/{organism}/exonerate/{protein}_{organism}_exonerate.txt"

        if not os.path.exists(file_path):
            print(f"Warning: File {file_path} not found. Skipping.")
            continue

        with open(file_path) as f:
            lines = f.readlines()

        current_header = None
        current_seq_lines = []
        recording = False

        for line in lines:
            line = line.strip()

            # New CDS block starts
            if line.startswith(">"):
                # Write previous sequence
                if current_header and current_seq_lines:
                    cds = ''.join(current_seq_lines).replace(" ", "").upper()
                    try:
                        protein_seq = str(Seq(cds).translate(to_stop=False, stop_symbol="X"))
                        output_fasta.write(f">{current_header}\n{protein_seq}\n")
                    except Exception as e:
                        print(f"Error translating {current_header}: {e}")

                current_header = line[1:].strip()
                current_seq_lines = []
                recording = True

            elif recording:
                # Stop recording if another alignment or unrelated info starts
                if (
                    line.startswith("C4 Alignment:")
                    or line.startswith("Command line")
                    or line.startswith("Hostname")
                    or line.startswith("--")
                    or line == ""
                ):
                    recording = False
                else:
                    current_seq_lines.append(line)

        # Handle last sequence in file
        if current_header and current_seq_lines:
            cds = ''.join(current_seq_lines).replace(" ", "").upper()
            try:
                protein_seq = str(Seq(cds).translate(table=trans_table, to_stop=False, stop_symbol="X"))
                output_fasta.write(f">{current_header}\n{protein_seq}\n")
            except Exception as e:
                print(f"Error translating {current_header}: {e}")

        output_fasta.close()
        print(f"Translation of {protein} from {organism} complete.")
