#!/usr/bin/env python3

import csv
import sys
import argparse
from pathlib import Path

#Generated by ChatGPT 5.5 in May 2025

# Script used for mapping DeepLoc 2.1 localizations into phylogenetic trees with predictions scores
# Only localization Mitochondrion and Plastid (and indecisive Mitochondrion|Plastid) were considered — other localizations are irrelevant for our purposes


VALID_LOCALIZATIONS = {
    "Plastid",
    "Mitochondrion",
    "Mitochondrion|Plastid"
}


def format_score(value):
    """
    Převede hodnotu na float a zaokrouhlí
    na dvě desetinná místa.
    """

    try:
        return f"{float(value):.2f}"
    except ValueError:
        return value


def load_localizations(csv_file):
    """
    Načte CSV tabulku a vrátí slovník:
    Protein_ID -> nový název taxonu
    """

    mapping = {}

    with open(csv_file, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)

        required_columns = {
            "Protein_ID",
            "Localizations",
            "Mitochondrion",
            "Plastid"
        }

        if not required_columns.issubset(reader.fieldnames):
            missing = required_columns - set(reader.fieldnames)
            raise ValueError(
                f"Chybí požadované sloupce v CSV: {', '.join(missing)}"
            )

        for row in reader:
            protein_id = row["Protein_ID"].strip()
            localization = row["Localizations"].strip()

            mito_value = format_score(
                row["Mitochondrion"].strip()
            )

            plastid_value = format_score(
                row["Plastid"].strip()
            )

            if localization not in VALID_LOCALIZATIONS:
                continue

            # Vytvoření nového názvu
            if localization == "Mitochondrion":

                new_name = (
                    f"{protein_id} "
                    f"{localization} "
                    f"{mito_value}"
                )

            elif localization == "Plastid":

                new_name = (
                    f"{protein_id} "
                    f"{localization} "
                    f"{plastid_value}"
                )

            elif localization == "Mitochondrion|Plastid":

                new_name = (
                    f"{protein_id} "
                    f"{localization} "
                    f"{mito_value}|{plastid_value}"
                )

            mapping[protein_id] = new_name

    return mapping


def rename_tree(tree_text, mapping):
    """
    Ve stromu přejmenuje taxony:
    original_name -> nový název
    """

    # Delší ID nahrazujeme první,
    # aby nedocházelo k částečným náhradám.
    sorted_ids = sorted(mapping.keys(), key=len, reverse=True)

    for protein_id in sorted_ids:
        tree_text = tree_text.replace(
            protein_id,
            mapping[protein_id]
        )

    return tree_text


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Přidá lokalizaci a skóre lokalizace "
            "k názvům sekvencí ve fylogenetickém stromu."
        ),
        epilog=(
            "Pouze lokalizace 'Plastid', 'Mitochondrion' "
            "a 'Mitochondrion|Plastid' jsou zahrnuty."
        )
    )

    parser.add_argument(
        "csv_file",
        help=(
            "CSV soubor obsahující sloupce "
            "Protein_ID, Localizations, "
            "Mitochondrion a Plastid"
        )
    )

    parser.add_argument(
        "tree_file",
        help="Fylogenetický strom ve formátu Newick"
    )

    args = parser.parse_args()

    csv_file = args.csv_file
    tree_file = args.tree_file

    # Načtení dat z CSV
    localization_map = load_localizations(csv_file)

    # Načtení stromu
    with open(tree_file, "r", encoding="utf-8") as f:
        tree_text = f.read()

    # Přejmenování taxonů
    renamed_tree = rename_tree(tree_text, localization_map)

    # Název output souboru
    tree_path = Path(tree_file)

    output_file = tree_path.with_name(
        tree_path.stem + "_renamed.tre"
    )

    # Uložení
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(renamed_tree)

    print(f"Hotovo. Výstup uložen do: {output_file}")


if __name__ == "__main__":
    main()