from Bio import SeqIO
import os

# Relocalization HMMER workflow No. 3
# Generated by ChatGPT

def deduplicate_fasta(input_file, output_file, mode="header"):
    """
    Remove duplicates from a FASTA file.

    mode:
        "sequence" — deduplicate based on identical sequence content
        "header"   — deduplicate based on identical FASTA headers (record.id)
    """
    print(f"Processing: {input_file}   [mode={mode}]")

    seen = set()
    unique_records = []
    total_count = 0

    for record in SeqIO.parse(input_file, "fasta"):
        total_count += 1

        if mode == "sequence":
            key = str(record.seq)
        elif mode == "header":
            key = record.id
        else:
            raise ValueError("Mode must be 'sequence' or 'header'")

        if key not in seen:
            seen.add(key)
            unique_records.append(record)

    with open(output_file, "w") as out:
        SeqIO.write(unique_records, out, "fasta")

    print(f"  Found {total_count} sequences")
    print(f"  Kept  {len(unique_records)} unique sequences")
    print(f"  Output written to: {output_file}\n")


if __name__ == "__main__":

    # ---------------------------------------------------------
    # CHOOSE DEDUPLICATION MODE HERE
    # ---------------------------------------------------------
    MODE = "header"      # options: "header" or "sequence"
    # ---------------------------------------------------------

    folder = "./proteins"

    for protein in os.listdir(folder):

        subdir = os.path.join(folder, protein)
        if not os.path.isdir(subdir):
            continue

        input_fasta = os.path.join(subdir, f"{protein}.fasta")
        if not os.path.isfile(input_fasta):
            continue

        output_fasta = os.path.join(subdir, f"{protein}_dedup.fasta")

        deduplicate_fasta(input_fasta, output_fasta, mode=MODE)
