from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
import os

# Nuclear assemblies search workflow No. 5

# Generated by ChatGPT

# Load organism → genetic code mapping
translation_table_file = "organisms_tables.txt"
genetic_code_map = {}
with open(translation_table_file) as f:
    for line in f:
        if ":" in line:
            org, code = line.strip().split(":")
            genetic_code_map[org.strip()] = int(code.strip())

# Load organism and protein lists
with open("organisms.txt") as f:
    organisms = [line.strip() for line in f if line.strip()]

with open("proteins.txt") as f:
    proteins = [line.strip().replace(".faa", "") for line in f if line.strip()]

for organism in organisms:
    mito_fasta = f"./organisms/{organism}/{organism}_genomic.fasta"

    if not os.path.exists(mito_fasta):
        print(f"[Warning] Missing genome for {organism}")
        continue

    if organism not in genetic_code_map:
        print(f"[Warning] No translation table for {organism}")
        continue

    trans_table = genetic_code_map[organism]

    # Load mitogenome into dictionary (in case of multi-sequence FASTA)
    genome_dict = SeqIO.to_dict(SeqIO.parse(mito_fasta, "fasta"))

    for protein in proteins:
        blast_file = f"./organisms/{organism}/tblastn/{protein}_{organism}_tblastn.txt"
        output_fasta = f"./organisms/{organism}/tblastn/{protein}_{organism}_seq.fasta"

        if not os.path.exists(blast_file):
            print(f"[Warning] Missing BLAST result for {protein} in {organism}")
            continue

        translated_records = []

        with open(blast_file) as f:
            for i, line in enumerate(f):
                if not line.strip():
                    continue
                parts = line.strip().split("\t")
                if len(parts) < 12:
                    continue  # malformed

                query_id, subject_id, perc_id, aln_len, mismatch, gapopen, qstart, qend, sstart, send, evalue, bitscore = parts

                sstart, send = int(sstart), int(send)
                strand = 1 if sstart <= send else -1
                start, end = min(sstart, send), max(sstart, send)

                if subject_id not in genome_dict:
                    print(f"[Warning] Subject ID {subject_id} not found in {mito_fasta}")
                    continue

                # Extract and translate
                seq = genome_dict[subject_id].seq[start - 1:end]  # 1-based BLAST coords
                if strand == -1:
                    seq = seq.reverse_complement()

                try:
                    protein_seq = seq.translate(table=trans_table, to_stop=False)
                except Exception as e:
                    print(f"[Error] Could not translate region {start}-{end} in {subject_id}: {e}")
                    continue

                header = f"{subject_id}_{start}_{end}_ribosomal_protein_{protein}_{organism}_tblastn_nuclear"
                record = SeqRecord(protein_seq, id=header, description="")
                translated_records.append(record)

        # Save to FASTA if we have any hits
        if translated_records:
            SeqIO.write(translated_records, output_fasta, "fasta")
            print(f"[OK] Saved translated proteins to: {output_fasta}")
        else:
            print(f"[Info] No hits found for {protein} in {organism}")
